os:
  - linux
#  - osx
dist: trusty
sudo: required
language: python
services:
  - docker

cache: pip
python:
  - "2.7"
  - "3.6"

before_install:
  - docker pull winnietsang/onnx-tensoflow:onnx1.3.0-tf1.13.1

script:
  - docker run winnietsang/onnx-tensoflow:onnx1.3.0-tf1.13.1 /bin/sh -c "git clone https://github.com/onnx/onnx-tensorflow.git;cd onnx-tensorflow;pip install -e .;python3 -m unittest discover test"
